---
title: Data Transformasi (menemukan penerbangan yang paling terlambat dan  yang berangkat
  paling awal, mengurutkan penerbangan untuk menemukan penerbangan tercepat (kecepatan
  tertinggi), mencari Penerbangan mana yang bepergian paling jauh dan Perjalanan mana
  yang paling singkat
author: "Prof. Dr. Suhartono, M. Kom @ Dini Kristianti, S. Kom"
date: "2 Maret 2021"
output: html_document
---

Sebelum kita mencari data penerbangan di bawah ini. Mari Kita Install dulu Libary nya
```{r}
library(tidyverse)
```
```{r}
library(nycflights13)
library(tidyverse)
```
Kita Cari data penerbangannya
```{r}
flights
#> # A tibble: 336,776 x 19
#>    year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
#>   <int> <int> <int>    <int>          <int>     <dbl>    <int>          <int>
#> 1  2013     1     1      517            515         2      830            819
#> 2  2013     1     1      533            529         4      850            830
#> 3  2013     1     1      542            540         2      923            850
#> 4  2013     1     1      544            545        -1     1004           1022
#> 5  2013     1     1      554            600        -6      812            837
#> 6  2013     1     1      554            558        -4      740            728
#> # . with 336,770 more rows, and 11 more variables: arr_delay <dbl>,
#> #   carrier <chr>, flight <int>, tailnum <chr>, origin <chr>, dest <chr>,
#> #   air_time <dbl>, distance <dbl>, hour <dbl>, minute <dbl>, time_hour <dttm>
```
Jika sudah muncul data penerbangan di atas. 

sekarang mengurutkan penerbangan untuk menemukan penerbangan yang paling terlambat. Temukan penerbangan yang berangkat paling awal.

```{r}
arrange(flights, desc(dep_time))
```

Penerbangan mana yang bepergian paling jauh?

```{r}
select(flights, dep_time, dep_delay, arr_time, arr_delay, origin, dest, hour, minute, time_hour, air_time)
filter(flights, hour >=23)
```
